"""Simple A2A Registry — Agent-to-Agent Registry Server.

A spec-compliant A2A Registry that accepts external agent registrations
with heartbeat-based liveness monitoring and task proxying.
"""

from simple_a2a_registry.models import (
    AgentCard,
    AgentCapabilities,
    AgentSkill,
    AgentInterface,
    AgentProvider,
    AgentExtension,
    AgentCardSignature,
    AuthenticationInfo,
    SecurityScheme,
    SecurityRequirement,
    APIKeySecurityScheme,
    HTTPAuthSecurityScheme,
    OAuth2SecurityScheme,
    OpenIdConnectSecurityScheme,
    MutualTlsSecurityScheme,
    OAuthFlows,
    AuthorizationCodeOAuthFlow,
    ClientCredentialsOAuthFlow,
    DeviceCodeOAuthFlow,
    ImplicitOAuthFlow,
    PasswordOAuthFlow,
    make_agent_card,
    make_agent_skill,
)
from simple_a2a_registry.auth import (
    AuthStore,
    AuthHandler,
    create_token,
    verify_token,
    _auth_middleware_factory as auth_middleware_factory,
    require_scope,
    SCOPES,
    TOKEN_EXPIRY_SECONDS,
)

__all__ = [
    "AgentCard",
    "AgentCapabilities",
    "AgentSkill",
    "AgentInterface",
    "AgentProvider",
    "AgentExtension",
    "AgentCardSignature",
    "AuthenticationInfo",
    "SecurityScheme",
    "SecurityRequirement",
    "APIKeySecurityScheme",
    "HTTPAuthSecurityScheme",
    "OAuth2SecurityScheme",
    "OpenIdConnectSecurityScheme",
    "MutualTlsSecurityScheme",
    "OAuthFlows",
    "AuthorizationCodeOAuthFlow",
    "ClientCredentialsOAuthFlow",
    "DeviceCodeOAuthFlow",
    "ImplicitOAuthFlow",
    "PasswordOAuthFlow",
    "make_agent_card",
    "make_agent_skill",
    "AuthStore",
    "AuthHandler",
    "create_token",
    "verify_token",
    "auth_middleware_factory",
    "require_scope",
    "SCOPES",
    "TOKEN_EXPIRY_SECONDS",
]