"""initial_schema

Revision ID: 01eb1637ac57
Revises: 
Create Date: 2026-05-27 00:57:08.081165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01eb1637ac57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('card_json', sa.Text(), nullable=False),
    sa.Column('heartbeat_at', sa.Float(), server_default='0', nullable=False),
    sa.Column('registered_at', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_agents_heartbeat', 'agents', ['heartbeat_at'], unique=False)
    op.create_table('auth_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_auth_codes')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('allowed_scopes', sa.Text(), nullable=False),
    sa.Column('agent_card_id', sa.String(length=255), server_default='', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_oauth_clients')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oauth_tokens',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_oauth_tokens')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_oauth_tokens_client_id', 'oauth_tokens', ['client_id'], unique=False)
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_comments')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_task_comments_task_id', 'task_comments', ['task_id', 'created_at'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_events')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_task_events_task_id', 'task_events', ['task_id', 'created_at'], unique=False)
    op.create_table('task_links',
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('child_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', name=op.f('pk_task_links')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='running', nullable=False),
    sa.Column('claim_lock', sa.String(length=255), nullable=True),
    sa.Column('claim_expires', sa.BigInteger(), nullable=True),
    sa.Column('worker_pid', sa.Integer(), nullable=True),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('ended_at', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_task_runs_task_id', 'task_runs', ['task_id', 'started_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='todo', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('workspace_kind', sa.String(length=50), nullable=True),
    sa.Column('workspace_path', sa.String(length=1024), nullable=True),
    sa.Column('claim_lock', sa.String(length=255), nullable=True),
    sa.Column('claim_expires', sa.BigInteger(), nullable=True),
    sa.Column('tenant', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('worker_pid', sa.Integer(), nullable=True),
    sa.Column('last_failure_error', sa.Text(), nullable=True),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.BigInteger(), nullable=True),
    sa.Column('current_run_id', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_tasks_assignee_status', 'tasks', ['assignee', 'status'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_tenant', 'tasks', ['tenant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_tenant', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_assignee_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_task_runs_task_id', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_table('task_links')
    op.drop_index('idx_task_events_task_id', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('idx_task_comments_task_id', table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index('idx_oauth_tokens_client_id', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_table('oauth_clients')
    op.drop_table('auth_codes')
    op.drop_index('idx_agents_heartbeat', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
