import axios from 'axios';
const api = axios.create({ baseURL: '', timeout: 15000 });
api.interceptors.request.use((c) => {
  const t = sessionStorage.getItem('token') || localStorage.getItem('token');
  if (t) c.headers.Authorization = `Bearer ${t}`;
  return c;
});
api.interceptors.response.use((r) => r, (e) => {
  const data = e.response?.data;
  if (e.response?.status === 401) { sessionStorage.removeItem('token'); localStorage.removeItem('token'); }
  console.warn('[API Error]', e.config?.url, e.response?.status, data?.detail||data||e.message);
  return Promise.reject(e);
});
export const getHealth = () => api.get('/health').then(r=>r.data);
export const listAgents = (p?:any) => api.get('/v1/agents',{params:p}).then(r=>r.data);
export const getAgent = (id:string) => api.get(`/v1/agents/${id}`).then(r=>r.data);
export const registerAgent = (b:any) => api.post('/v1/agents',b).then(r=>r.data);
export const unregisterAgent = (id:string) => api.delete(`/v1/agents/${id}`).then(r=>r.data);
export const toggleAgent = (id:string) => api.post(`/v1/agents/${id}/toggle`).then(r=>r.data);
export const updateAgent = (id:string,b:any) => api.patch(`/v1/agents/${id}`,b).then(r=>r.data);
export const listV1Tasks = (p?:any) => api.get('/v1/tasks',{params:p}).then(r=>r.data);
export const listV2Tasks = (p?:any) => api.get('/v2/tasks',{params:p}).then(r=>r.data);
export const getV2Task = (id:string) => api.get(`/v2/tasks/${id}`).then(r=>r.data);
export const createV2Task = (b:any) => api.post('/v2/tasks',b).then(r=>r.data);
export const blockV2Task = (id:string,r?:string) => api.post(`/v2/tasks/${id}/block`,{reason:r});
export const getV2Stats = () => api.get('/v2/stats').then(r=>r.data);
export const listClients = (p?:any) => api.get('/admin/clients',{params:p}).then(r=>r.data);
export const createClient = (b:any) => api.post('/admin/clients',b).then(r=>r.data);
export const deleteClient = (id:string) => api.delete(`/admin/clients/${id}`).then(r=>r.data);
export const toggleClient = (id:string) => api.post(`/admin/clients/${id}/toggle`).then(r=>r.data);
export const listAuditLog = (p?:any) => api.get('/admin/audit',{params:p}).then(r=>r.data);
export const listAuditLogs = (p?:any) => api.get('/admin/audit',{params:p}).then(r=>r.data);
export const getAdminStats = () => api.get('/admin/agent-stats').then(r=>r.data);
export const login = (u:string,p:string) => api.post('/api/login',{username:u,password:p}).then(r=>r.data);
export const logout = () => api.post('/api/logout').then(r=>r.data);
export const getMe = () => api.get('/api/me').then(r=>r.data);
export const listUsers = (p?:any) => api.get('/admin/users',{params:p}).then(r=>r.data);
export const createUser = (b:any) => api.post('/admin/users',b).then(r=>r.data);
export const updateUser = (u:string,b:any) => api.put(`/admin/users/${u}`,b).then(r=>r.data);
export const deleteUser = (u:string) => api.delete(`/admin/users/${u}`).then(r=>r.data);
export const toggleUser = (id:string) => api.post(`/admin/users/${id}/toggle`).then(r=>r.data);
export const getSettings = () => api.get('/admin/settings').then(r=>r.data);
export const updateSettings = (b:any) => api.put('/admin/settings',b).then(r=>r.data);
export const reloadConfig = () => api.post('/admin/config/reload').then(r=>r.data);
export default api;
